=== blinkylights23/jsonConverter/schema/jsonConverter/0.0.1/template.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://raw.githubusercontent.com/blinkylights23/jsonConverter/master/schema/jsonConverter/0.0.1/template.json",
  "title": "A jsonConverter template",
  "description": "Holds attributes of a jsonConverter template, to be used to instantiate a converter",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "schemaVersion": {
      "type": "string",
      "description": "The version of the JSON schema definition used for this template",
      "enum": ["0.0.1"]
    },
    "jsonConverterVersion": {
      "type": "string",
      "description": "The version of jsonConverter this template works with",
      "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(-(0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(\\.(0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\\+[0-9a-zA-Z-]+(\\.[0-9a-zA-Z-]+)*)?$"
    },
    "version": {
      "type": "string",
      "description": "The version of the template (not the schema or the module)",
      "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(-(0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(\\.(0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\\+[0-9a-zA-Z-]+(\\.[0-9a-zA-Z-]+)*)?$"
    },
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "querySyntax": {
      "type": "string",
      "description": "The querying tool used for selecting data from the source document",
      "enum": ["jmespath"]
    },
    "mappings": {
      "type": "array",
      "items": {
        "$ref": "https://raw.githubusercontent.com/blinkylights23/jsonConverter/master/schema/jsonConverter/0.0.1/mapping.json"
      }
    }
  },
  "required": ["mappings", "version"]
}

=== blinkylights23/jsonConverter/examples/starwars/lib/characterTemplate.json
{
  "version": "0.0.0",
  "id": "characterConverter",
  "name": "Character Converter",
  "description": "Converts data from SWAPI to our target format",
  "mappings": [
    { "path": "characterName", "query": "name", "processors": ["trim"] },
    {
      "path": "appearedIn",
      "query": "films",
      "processors": [
        { "processor": "map", "args": ["fetch"] },
        { "processor": "query", "args": ["[].title"] }
      ]
    },
    {
      "path": "homeworld",
      "query": "homeworld",
      "processors": ["fetch", { "processor": "query", "args": ["name"] }]
    },
    {
      "path": "bio.height",
      "query": "height",
      "processors": ["cm2ft"]
    },
    {
      "path": "bio.weight",
      "query": "mass",
      "processors": ["kg2lbs"]
    },
    {
      "path": "bio.eyes",
      "query": "eye_color"
    },
    {
      "path": "bio.gender",
      "query": "gender"
    },
    {
      "path": "bio.skin",
      "query": "skin_color"
    },
    {
      "path": "bio.hair",
      "query": "hair_color"
    }
  ]
}
